// Swiss bridge (web) — backend calls from the React frontend.
//
// ONE App.jsx, ONE backend convention across targets: the developer writes
// plain native-typed Ezy functions (`fn bump() -> int`, `fn add(a:int,b:int)`),
// and calls them the SAME way everywhere:
//
//   import { ezy } from 'swiss';
//   const n = ezy.call('bump');            // sync on BOTH web and gtk
//
// On web the async wasm load happens once inside Swiss `render()` bootstrap, so
// by the time the App mounts `ezy.call` is synchronous (handlers always run
// after mount). On gtk the translator turns `ezy.call('bump')` into a direct C
// call. Either way the App source is identical.
//
// Types come from backend.sig.json (generated by swiss-sig from the .ez): Ezy
// `int` is 64-bit, so it crosses the wasm boundary as BigInt — we marshal
// numeric args to BigInt and hand back plain Numbers.

const isInt = (t) => t === 'int' || t === 'bool' || t === 'char';

function marshalArg(type, v) {
  if (type === 'string') return v;
  if (type === 'float') return Number(v);
  if (isInt(type)) return BigInt(v);
  return BigInt(v); // pointers/handles
}

function makeImpl(M, sigs) {
  if (!M.ccall) throw new Error('swiss: ezy module has no ccall (build with --platform web-esm)');
  return {
    call(fn, ...args) {
      const sig = sigs[fn];
      if (!sig) {
        // no signature: best-effort numeric (BigInt) call
        const f = M['_' + fn];
        if (!f) throw new Error('swiss: unknown backend fn ' + fn);
        const r = f(...args.map((a) => (typeof a === 'number' ? BigInt(a) : a)));
        return typeof r === 'bigint' ? Number(r) : r;
      }
      const argT = sig.args.map((t) => (t === 'string' ? 'string' : 'number'));
      const vals = args.map((v, i) => marshalArg(sig.args[i], v));
      const retT = sig.ret === 'string' ? 'string' : sig.ret === 'void' ? null : 'number';
      const r = M.ccall(fn, retT, argT, vals);
      if (sig.ret === 'void') return undefined;
      return typeof r === 'bigint' ? Number(r) : r;
    },
    module: M,
  };
}

// ── the singleton App code imports ──
let impl = null;
export const ezy = {
  call(fn, ...args) {
    if (!impl) throw new Error('swiss: ezy backend not ready — call inside handlers/effects, after render()');
    return impl.call(fn, ...args);
  },
  get ready() { return !!impl; },
};

export function setBackend(i) { impl = i; }

// load an emscripten factory + signatures into a ready impl (used by render bootstrap)
export async function connectEzy(factory, sigs = {}) {
  const M = await factory();
  const i = makeImpl(M, sigs);
  return i;
}

export default ezy;
